name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Pages
    # I feel like this isn't being done
      uses: actions/configure-pages@v2

    - name: Use Node.js 16.10
      uses: actions/setup-node@v1
      with:
        node-version: '16.10'

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/ase/ --message="Deploy to Github Pages" --no-silent