name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.10
      uses: actions/setup-node@v1
      with:
        node-version: '16.10'

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm ci
        npm run ng -- deploy --base-href=/ASE/ --message="Automated Deploy to Github Pages" --no-silent --name="GH Action Bot" --email=gh.action@example.org